"""
Authentication Constants
"""

ACCESS_TOKEN_EXPIRE_MINUTES = 15

REFRESH_TOKEN_EXPIRE_DAYS = 7

PASSWORD_MIN_LENGTH = 8

JWT_ALGORITHM = "HS256"

PROFILE_IMAGE_FOLDER = "media/profile"

DEFAULT_PROFILE_IMAGE = None